[build]
  functions = "netlify/functions"
  publish = "static"  # Static assets to be served by Netlify's CDN. Folder defaults to public

[functions]
  node_bundler = "esbuild"
  included_files = [
    "static/*/**"  # Include all files in static for server-side access
  ] 
[dev]
  port = 4000

[[redirects]]
  from = "/maps/*"
  to = "/.netlify/functions/server?path=maps/:splat"
  status = 200

