[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  port = 4000

[[redirects]]
  from = "/maps/*"
  to = "/.netlify/functions/server?path=maps/:splat"
  status = 200

